repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: detect-private-key
-   repo: local
    hooks:
    -   id: scalafmt
        name: scalafmt
        entry: make hook-scalafmt
        language: system
        files: .scala$
        types: [file, text]
    -   id: scalastyle
        name: scalastyle
        entry: make hook-scalastyle
        language: system
        files: .scala$
        types: [file, text]
